config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root "pages#index" 
  get "/home/about" => "pages#about"
  get "/home/delivery" => "pages#delivery"
  get "/home/questions" => "pages#questions"
  
  resources :pages
  resources :products, only: [:index, :show] 
  resources :bulletins, only: [:index, :show]
  resources :contacts 


  namespace :admin, path: "en1070416" do
    resources :products
    root "products#index"
    resources :bulletins
    resources :categories
    resources :contacts, only: [:index, :destroy]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bulletin.rb
class Bulletin < ApplicationRecord
  validates_presence_of :title

  belongs_to :category, optional: true
  mount_uploader :picture, PictureUploader

end

app/models/contact.rb
class Contact < ApplicationRecord
  validates_presence_of :name, :message
  validates :phone, format:{with: /\A09\d{8}\Z/}
  validates :email, format: { with: /\A[^@]+@[^@]+\z/}

end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :product
  mount_uploader :avatar, AvatarUploader

end

app/models/product.rb
class Product < ApplicationRecord
  validates_presence_of :name
  has_many :photos, dependent: :destroy

  accepts_nested_attributes_for :photos, :allow_destroy => true
  #之後要做nested form，先設定接受變更photo底下的attribute
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def admin?
    self.role == "admin"
  end
  
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_action :authenticate_user!
  before_action :authenticate_admin

    private
  def authenticate_admin
    if !current_user.admin?
      flash[:alert]="not allow"
      redirect_to root_path
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
end

app/controllers/bulletins_controller.rb
class BulletinsController < ApplicationController
  def index
    @bulletins = Bulletin.order(created_at: :desc).page(params[:page]).per(8)
  end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def index
    @contact = Contact.new
  end


  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      flash[:notice] = "Message was successfully created 訊息傳送成功"
      redirect_to contacts_path
      UserMailer.notify_contact_create(@contact).deliver_now!

    else
      flash.now[:alert] = "Message was failed created 請重新檢查欄位"
      render :index
    end
  end

  private

  def contact_params
    params.require(:contact).permit(:name, :phone, :email, :message)
  end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @bulletins = Bulletin.order(created_at: :desc).limit(1)
    @products = Product.all  
  end

  def show
    @product = Product.find(params[:id])
    @photos = @product.photos.all
  end
  
  
  def about
  end

  def delivery
  end

  def questions
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show]

  def index
    @products = Product.all
  end

  def show
    @photos = @product.photos.all
    @products = Product.where.not(params[:id])
  end

  private
  def set_product
    @product = Product.find(params[:id])
  end
end

app/helpers/admin/bulletins_helper.rb
module Admin::BulletinsHelper
end

app/helpers/admin/contacts_helper.rb
module Admin::ContactsHelper
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bulletins_helper.rb
module BulletinsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/_footer.html.erb
<div class="footer container-fluid  bg-dark">
  <div class="container">
    <div class="footer-content pt-3">
      <div class="footer-icon">
        <div onclick="topFunction()" id="myBtn" title="Go to top"><i class="fas fa-arrow-circle-up fa-2x"></i></div>
        
      </div>

      <!-- mobile -->
      <div class="footer-info d-block d-md-none ">
        <div class="footer-col text-center">
          <p>LINE訂餐：@quo1137i</p> 
          <p>外送專線：0900-792620</p>
          <p>營業時間：週一～週五 09:30-17:00</p>
          <p>自取地址：新北市新莊區中正路366號(工作室不對外開放)</p>
        </div>
      </div>
      
      <!-- desktop -->
      <div class="d-none d-md-block mb-2">
        <div class="row footer-info d-inline-flex  bd-highlight px-4 mr-4">
          <div class="footer-col bd-highlight mr-4">
            <p>SERVICE</p>
            <p>LINE訂餐：@quo1137i</p> 
            <p>外送專線：0900-792620</p>
          </div>
          <div class="footer-col bd-highlight">
            <p>ABOUT</p>
            <p>營業時間：週一～週五 09:30-17:00</p>
            <p>自取地址：<a href="https://goo.gl/maps/C2j1obBZVfL2" target="_blank">新北市新莊區中正路366號1F</a>(工作室不對外開放)</p>
          </div>
        </div>
      </div>

      <div class="clearfix"></div>
    </div>
    <div class="footer-social-icon text-center mb-2">
      <a href="https://www.facebook.com/enjoyrice/" target="_blank"><i class="fab fa-facebook-f fa-2x"></i></a>
      <a href="https://www.instagram.com/enjoyrice.tw/" target="_blank"><i class="fab fa-line fa-2x"></i></a>
      <a href="https://line.me/R/ti/p/%40kuo1137i" target="_blank"><i class="fab fa-instagram fa-2x"></i></a>
    </div>
  </div>
    
    <div class="copyright text-center ">
      <p><small>&copy;2018 EnjoyRice玩飯職人 版權所有 | website design by mspink</small></p>
    </div> 
</div>

app/views/layouts/_navbar.html.erb
<div class="enav fixed-top navbar-dark bg-dark">
  <div class="container">
    <nav class="d-flex justify-content-md-start justify-content-between mx-2">
      <div class="order-2 order-md-1">
          <div class="navbar-brand">
            <%= link_to root_path do %>
              <div class="brand-logo d-block d-md-none">
                 <img src="<%= image_path('logo.png') %>" alt="App Logo"  >
              </div>
              <div class="brand-logo d-none d-md-block">
                 <img src="<%= image_path('logo.png') %>" alt="App Logo"  >
              </div>
            <% end %>
          </div>
      </div>
      <div class="order-1 order-md-2 d-md-none bar">
        <div class="bar navbar-toggler" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <i class="fas fa-bars"></i></div>
      </div>

      <div class="order-1 order-md-2 mr-md-auto d-none d-md-block">
        <ul class="navbar list-unstyled">
          <li class="nav-item">
            <%= link_to '關於我們', home_about_path,class: "nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to '玩飯美味', products_path,class: "nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to '玩飯快訊', bulletins_path,class: "nav-link" %>
          </li>

          <li>
          <div class="dropdown show">
            <a class="btn dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">服務資訊</a>

          <div class="dropdown-menu bg-dark" aria-labelledby="dropdownMenuLink">
          <%= link_to '外送範圍', home_delivery_path, class: "dropdown-item" %>
          <%= link_to '聯絡我們', contacts_path, class: "dropdown-item" %>
          <%= link_to '訂購Q&A', home_questions_path, class: "dropdown-item" %>
          </div>
        </div>
          </li>

          <li>
            <% if current_user&.admin? %>
              <%= link_to 'Admin Panel', admin_root_path %>
              <%= link_to'登出', destroy_user_session_path, method: :delete %>

              <% end %>
          </li>
        </ul>
      </div>
        <div class="order-3 order-md-3 mr-md-auto d-md-none d-block">
          <p> </p>
        </div>
    </nav>     
  </div>
</div>

<!-- mobile -->

    <nav class="ernav collapse navbar-collapse bg-dark mt-5 " id="navbarSupportedContent">
        <ul class="navbar-nav ml-3 list-unstyled">
          <li class="nav-item">
            <%= link_to '關於我們', home_about_path,class: "nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to '玩飯美味', products_path,class: "nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to '玩飯快訊', bulletins_path,class: "nav-link" %>
          </li>

          <li>
          <div class="dropdown show">
            <a class="nav-link dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">服務資訊</a>

            <div class="dropdown-menu bg-dark border-0" aria-labelledby="dropdownMenuLink">
              <%= link_to '外送範圍', home_delivery_path, class: "dropdown-item " %>
              <%= link_to '聯絡我們', contacts_path, class: "dropdown-item" %>
              <%= link_to '訂購QA', home_questions_path, class: "dropdown-item" %>
            </div>
          </div>
          </li>
          <!-- 會員資訊 -->
          <li>
   
            <% if current_user&.admin? %>
              <%= link_to 'Admin Panel', admin_root_path %>
            <% end %>

          </li>

        <div class="footer-social-icon mt-5 mb-3 p-2 d-block d-md-none">
          <a href="https://www.facebook.com/enjoyrice/" target="_blank"><i class="fab fa-facebook-f fa-lg"></i></a>
          <a href="https://www.instagram.com/enjoyrice.tw/" target="_blank"><i class="fab fa-line fa-lg"></i></a>
          <a href="https://line.me/R/ti/p/%40kuo1137i" target="_blank"><i class="fab fa-instagram fa-lg"></i></a>
        </div>

      </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EStore</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
        <!-- header -->
    <header>
      <%= render partial: "layouts/navbar" %>
    </header>

    
    <!-- Notice bar -->   
    <% if flash[:notice] %>
      <div id="notice_wrapper">
        <p class="notice"><%= notice %></p>
      </div>
    <% elsif flash[:alert] %>
      <div id="notice_wrapper">
        <p class="alert"><%= alert %></p>
      </div>
    <% end %>
   

    <%= yield %>
  </body>
    
  <footer>
    <%= render partial: "layouts/footer" %>
  </footer>

  </body>
</html>

app/views/pages/_menu.html.erb
<div class="col-10 col-sm-6">
  <div class="box px-0 mb-5">
    <%= link_to products_path do %>
    <div class="menu-img">
        <img src="https://s3-ap-northeast-1.amazonaws.com/www.enjoyrice.com/product/menu-chicken.jpg" alt="玩飯餐盒" class="img-fluid">
    </div>

    <div class="menu-content text-center">
      <h5 class="menu-title mt-2 mb-1 "> 白玉嫩嫩雞 </h5>
      <p class="mb-1 gray-color"><small> Chicken breast with spices </small></p>
    </div>

    <% end %>
  </div>
</div>


<div class="col-10 col-sm-6">
  <div class="box px-0 mb-5">
    <%= link_to products_path do %>
    <div class="menu-img">
      <img src="https://s3-ap-northeast-1.amazonaws.com/www.enjoyrice.com/product/menu-pork.jpg" alt="玩飯餐盒" class="img-fluid">
    </div>

    <div class="menu-content text-center">
      <h5 class="menu-title mt-2 mb-1 "> 白玉嫩嫩雞</h5>
      <p class="mb-1 gray-color"><small> Chicken breast with spices</small></p>
    </div>
    <% end %> 
  </div>
</div>




<div class="col-10 col-sm-6">
  <div class="box px-0 mb-5">
    <%= link_to products_path do %>
    <div class="menu-img">
      <img src="https://s3-ap-northeast-1.amazonaws.com/www.enjoyrice.com/product/menu-salmon.jpg" alt="玩飯餐盒" class="img-fluid">
    </div>

    <div class="menu-content text-center">
      <h5 class="menu-title mt-2 mb-1 "> 白玉嫩嫩雞 </h5>
      <p class="mb-1 gray-color"><small> Chicken breast with spices </small></p>
    </div>
    <% end %> 
  </div>
</div>


<div class="col-10 col-sm-6">
  <div class="box px-0 mb-5">
    <%= link_to products_path do %>
    <div class="menu-img">
      <img src="https://s3-ap-northeast-1.amazonaws.com/www.enjoyrice.com/product/menu-steak.jpg" alt="玩飯餐盒" class="img-fluid">

    </div>

    <div class="menu-content text-center">
      <h5 class="menu-title mt-2 mb-1 "> 白玉嫩嫩雞 </h5>
      <p class="mb-1 gray-color"><small> Chicken breast with spices </small></p>
    </div>
    <% end %> 
  </div>
</div>

app/views/pages/about.html.erb
  <!-- about background -->
  <div class="about_bg top_bg">
    <img src="https://s3-ap-northeast-1.amazonaws.com/www.enjoyrice.com/banner/topbanner-2-lg.jpg" alt="玩飯餐盒" class="img-fluid d-none d-md-block">
    <img src="https://s3-ap-northeast-1.amazonaws.com/www.enjoyrice.com/banner/topbanner-2-sm.jpg" alt="玩飯餐盒" class="img-fluid d-block d-md-none">
    <div class="overlay"></div>
    <div class="toptitle">
      <div class="quotes-inner">
        <h5 class="font-weight-light mb-1">如果說，有種飲食，少點油，少點負擔...</h5>
      </div>
    </div>
  </div>

<div class="container">  
  <!-- about us -->
  <section id="about_us">
    <h4 class="text-center py-5">“健康與美味不必二選一“</h4>
    <div class="about-content row d-flex px-5 px-md-2 justify-content-center"> 

      <div class="about-content col-md-4 col-12"> 
        <div class="row justify-content-center">   
          <div class="col-md-10 col-6 mb-4">
            <img src="https://s3-ap-northeast-1.amazonaws.com/www.enjoyrice.com/banner/about-1.png" alt="玩飯餐盒" class="img-fluid">
          </div>
          <div class="col-md-10 col-6 mb-4 py-3">
            <div class="text-center">
              <h5>食材真實的味道</h5>
              <p class="gray-color">低鈉、低油、無味精，天然無添加，依然風味濃郁，讓我們一起給身體健康純粹的美味。</p>
            </div>
          </div>
        </div>
      </div>

      <div class="about-content col-md-4 col-12"> 
        <div class="row justify-content-center"> 
          <div class="col-md-10 col-6 mb-4">
            <img src="https://s3-ap-northeast-1.amazonaws.com/www.enjoyrice.com/banner/about-2.png" alt="玩飯餐盒" class="img-fluid">
          </div>
          <div class="col-md-10 col-6 mb-4 py-3">
            <div class="text-center">
              <h5 >當令五色蔬果</h5>
              <p class="gray-color">依當令時節搭配五色蔬果，青紅黃白黑，提升身體五力！</p>
            </div>
          </div>
        </div>
      </div>

      <div class="about-content col-md-4 col-12"> 
        <div class="row justify-content-center"> 
          <div class="col-md-10 col-6 mb-4">
            <img src="https://s3-ap-northeast-1.amazonaws.com/www.enjoyrice.com/banner/about-3.png" alt="玩飯餐盒" class="img-fluid">
          </div>
          <div class="col-md-10 col-6 mb-4 py-3">
            <div class="text-center">
              <h5>低溫烹調 五星美味</h5>
              <p class="gray-color">低溫熟成，確保食材鮮度，保留營養成分，肉汁飽滿、不乾柴！</p>
            </div>
          </div>
        </div>
      </div>
  </section>

  
</div> 
  <!-- about quote -->
  <section id="about-quote">
  <div class="menu-quote mb-5">
    <div class="quote-bg">
      <img src="https://s3-ap-northeast-1.amazonaws.com/www.enjoyrice.com/banner/mdbanner-1.jpg" alt="玩飯餐盒" class="img-fluid">
      <div class="overlay"></div>
      <div class="quotes">
        <div class="quotes-inner">
          <h5 class="font-weight-light">Bon appetit</h5>
          <p class="font-weight-light">享受美食，不需要理由</p>
        </div>
      </div>
    </div>
  </div>
  </section>

  <!-- about col-->
  <div class="container">

    <div class="about-col row d-flex my-5">
      <div class="about-col-item col align-self-center  text-center">
        <h5>職人手作餐盒</h5>
        <p class="gray-color">我們只給你天天都想吃的健康美食！</p>
        <div><%= link_to'MENU', products_path, class: "btn-mb-w mx-4 px-4 er-link" %></div>
      </div>
      <div class="about-col-item col p-1">
        <img src="  https://s3-ap-northeast-1.amazonaws.com/www.enjoyrice.com/banner/about-4.jpg" alt="會議餐盒" class="img-fluid">    
      </div>
    </div>
  </div>


  <!-- about-footer -->
  <div class="gray-bg mb-5">
    <div class="container">
      <h5 class="text-center">商務餐盒，會議便當</h5>
      <p class="gray-color">如果說，有種飲食，少點油，少點負擔，依然美味...<br>
         如果說，有種餐盒，跟下午茶一樣美好卻不用擔心熱量太高...<br>
         如果說，健康不再與沒味道劃上等號...<br><br>
         舌頭是獲得幸福的最短距離，我們用一顆真誠的心創造沒有負擔的天然料理。不想被社會潮流推著走，想呈現最單純的原味，傳遞真實、健康的飲食概念。<br>
         『用心傾聽身體的需求，選擇身體需要的食物』，只想給你真的食物。玩飯餐盒低鈉、低油、天然、無不必要的人工添加物，依然風味濃郁，讓我們給予身體一個健康純粹的美味。</p>
    </div>
  </div>

app/views/pages/delivery.html.erb
  <div class="about_bg top_bg">
    <img src="https://s3-ap-northeast-1.amazonaws.com/www.enjoyrice.com/banner/topbanner-4-lg.jpg" alt="玩飯餐盒" class="img-fluid d-none d-md-block">
    <img src="https://s3-ap-northeast-1.amazonaws.com/www.enjoyrice.com/banner/topbanner-4-lg.jpg" alt="玩飯餐盒" class="img-fluid d-block d-md-none">
    <div class="overlay"></div>
    <div class="toptitle-c">
      <div class="quotes-inner">
        <h3 class="mb-1">location</h3>
      </div>
    </div>
  </div>

  <div class="container">

  <div class="row contact-toptitle mt-5">
    <ol class="contact-title col-12 d-flex justify-content-center pr-md-3 pr-0">
      <li class="front-title">外送範圍</li>
      <li class="front-title"><%= link_to '訂購Q&A', home_questions_path, class: "gray-text" %> </li>
      <li><%= link_to '聯絡我們', contacts_path, class: "gray-text" %></li>
    </ol>
  </div>
  
  <!-- 地圖 -->

  <div class="delivery-img text-center">
    <a href="https://goo.gl/maps/C2j1obBZVfL2" target="_blank"><img src="https://s3-ap-northeast-1.amazonaws.com/www.enjoyrice.com/banner/deliver.jpg" alt="外送範圍" class="img-fluid"></a>
  </div>

  <div class="reserve-inner my-4 py-2">
    <ul>
      <li>為保持餐點品質，餐盒配送範圍如圖</li>
      <li><strong>紅色區域：</strong>板橋區、新莊區訂購五個起免運</li>
      <li><strong>藍色區域：</strong>2500元起即可外送</li>
      <li>區域範圍外：3500元起即可外送</li>
      <li>大量需求、會議餐盒、商務餐盒請提前於LINE詢問</li>
      <li>訂購1~4僅提供自取，請自備環保袋取餐，未攜帶者售紙袋$5元/個</li>
      <li>自取地址：<a href="https://goo.gl/maps/C2j1obBZVfL2" target="_blank">新北市新莊區中正路366號1F</a>（工作室不對外開放）</li>
    </ul>
  </div>

  <div class="d-flex justify-content-center btn-group mt-4 py-2">
    <div><%= link_to '訂購Q&A', home_questions_path, class:"btn-mb-w mx-4 px-4 er-link" %></div>
    <div><%= link_to '商務餐盒', products_path, class:"btn-mb-w mx-4 px-4 er-link" %></div>
  </div>

  </div>

app/views/pages/index.html.erb
<!-- home background -->
<section id = "content">
  <div class="menu-bg top_bg">
    <img src="https://s3-ap-northeast-1.amazonaws.com/www.enjoyrice.com/banner/index-lg.jpg" alt="玩飯餐盒" class="img-fluid d-none d-md-block">
    <img src="https://s3-ap-northeast-1.amazonaws.com/www.enjoyrice.com/banner/index-sm.jpg" alt="玩飯餐盒" class="img-fluid d-block d-md-none">
    <div class="overlay"></div>
    <div class="toptitle">
      <div class="quotes-inner">
        <h5 class="font-weight-light mb-1"> &quot;幸福、美好、無負擔的日常飲食&quot;</h5>
      </div>
    </div>
  </div>
</section>

<div class="container">
  <!-- bulletin -->
  <%= link_to bulletins_path, class:"link-n" do %> 
    <div class="row justify-content-center">
      <div class="index-bulletin d-flex col-md-8 col-10 mt-5 p-2">
        <div id="bulletin">
          <div class="bulletin-inner">
          <h5 class="d-inline"><i class="fas fa-bullhorn"></i></h5>
          <%= render partial: "bulletins/first" %>
          </div>   
        </div>
      </div>     
    </div>
  <% end %>
  
</div>

  <!-- about -->
  <section id="about">
    <div class="index-title my-5">
      <hr><span class="index-span">關於我們</span>
    </div>
    <div class="quote-bg">
      <img src="  https://s3-ap-northeast-1.amazonaws.com/www.enjoyrice.com/banner/index-lg-2.jpg" alt="會議餐盒" class="img-fluid d-none d-md-block">
      <img src="https://s3-ap-northeast-1.amazonaws.com/www.enjoyrice.com/banner/index-sm-2.jpg" alt="會議餐盒" class="img-fluid d-md-none">
      <div class="overlay"></div>
      <div class="quotes">
        <div class="quotes-inner">
        <h5>“我們想給你真的食物”</h5>
        </div>
      </div>
    </div>
  </section>

  <!-- menu -->
  <section id="menu">
    <div class="index-title my-5">
      <hr><span class="index-span">商務餐盒</span>
    </div>
    
    <div class="container">
      <div class="menu-col">
      <div class="row justify-content-center">
       <%= render partial: "menu" %>
      </div>
      </div>
    </div>

  </section>

  <!-- reserve -->
  <section class="reserve py-2">
    <div class="index-title my-5">
      <hr><span class="index-span">預定提醒</span>
    </div>
    <div class="reserve-content">
      <div class="gray-bg">
        <div class="container">
          <ul class="reserve-inner">
            <li>訂餐方式:目前僅提供Line預定(ID:@kuo1137i)</li>
            <li>提前預訂:因餐點製備時間較長，請於1~3天前預訂</li>
            <li>外送服務:板橋、新莊5個即可免運，其餘地區請看外送範圍</li>
            <li>週末、晚餐如需大量訂購請私訊我們</li>
          </ul>
        </div>
        <div class="d-flex justify-content-center btn-group">
          <a href="https://line.me/R/ti/p/%40kuo1137i" class= "text-center btn-mb mx-4 px-4 er-link" target="_blank">線上預訂</a>
          <div><%= link_to '訂購Q&A', home_questions_path, class:"btn-mb mx-4 px-4 er-link" %></div>
        </div>
      </div>
    </div>    
  </section>

  <!-- blog -->

</div>

app/views/pages/questions.html.erb
  <div class="about_bg top_bg">
    <img src="https://s3-ap-northeast-1.amazonaws.com/www.enjoyrice.com/banner/topbanner-4-lg.jpg" alt="玩飯餐盒" class="img-fluid d-none d-md-block">
    <img src="https://s3-ap-northeast-1.amazonaws.com/www.enjoyrice.com/banner/topbanner-4-lg.jpg" alt="玩飯餐盒" class="img-fluid d-block d-md-none">
    <div class="overlay"></div>
    <div class="toptitle-c">
      <div class="quotes-inner">
        <h3 class="mb-1">Q&amp;A</h3>
      </div>
    </div>
  </div>

<div class="container">
  <div class="row contact-toptitle mt-5">
    <ol class="contact-title col-12 d-flex justify-content-center pr-md-3 pr-0">
      <li class="front-title"><%= link_to '外送範圍', home_delivery_path, class:"gray-text" %></li>
      <li class="front-title">訂購Q&amp;A</li>
      <li><%= link_to '聯絡我們', contacts_path, class: "gray-text" %></li>
    </ol>
  </div>

  <div class="questions m-3">
    <div class="q-bar bg-dark">常見訂購問題Q&amp;A</div>
    <div class="q-content mt-3">
      <p >Q:請問店面在哪裡？</p>
      <p >A:我們是工作室，目前尚未對外開放，餐點均須提前預約。</p>
    </div>
    <div class="q-content">
      <p >Q:請問可以外送嗎？</p>
      <p >A:我們提供自取及外送服務，板橋、新莊五個即可免費外送，台北市3500元起即可免費外送，其餘請於:Line詢問客服(ID:@quo1137i)。</p>
    </div>
    <div class="q-content">
      <p>Q:請問如何訂餐？</p>
      <p>A:目前開放Line(ID:@quo1137i)及電話預訂(0900-079620)。</p>
    </div>
    <div class="q-content">
      <p>Q:請問可以當日訂餐嗎？</p>
      <p>A:因餐點備置時間較長，部分蔬果當日新鮮採買，建議提前1-3天預訂。</p>
    </div>
    <div class="q-content">
      <p>Q:大量訂購需要多久前預訂？</p>
      <p>A:需求大量、茶會外燴、活動餐盒請提前3-5日以上詢問檔期及合作方式。</p>
    </div>
    <div class="q-content">
      <p >Q:請問晚餐有營業嗎？</p>
      <p >A:目前僅提供午餐，晚餐餐盒大量訂購請於Line詢問客服(ID:@quo1137i)。</p>
    </div>
    <div class="q-content">
      <p>Q:請問週末可以訂購嗎？</p>
      <p>A:目前營業時間為週一～週五午餐時段，活動、會議餐盒假日滿3500以上可彈性調整，須事先於Line詢問客服(ID:@quo1137i)。</p>
    </div>
    <div class="q-content">
      <p>Q:請問可以打統編嗎？</p>
      <p>A:我們有提供三聯式統一發票</p>
    </div>
  </div>

  <div class="d-flex justify-content-center btn-group mt-5">
    <a href="https://line.me/R/ti/p/%40kuo1137i" class= "text-center btn-mb-w mx-4 px-4 er-link" target="_blank">線上預訂</a>
    <div><%= link_to'外送範圍', home_delivery_path, class:"btn-mb-w mx-4 px-4 er-link" %></div>
  </div>
</div>